### ISSUE TITLE
KeyError: 'Unrecognized norm type DCN' for build_conv_layer

### ISSUE THREAD

**Issue by zehuichen123** [open-mmlab/mmcv#627]
Hi, I am trying to use mmcv wrapper build_conv_layer to build DCN following the code in mmdet like this:
```python
In [1]: from mmcv.cnn import build_conv_layer

In [2]: dcn = {'type': 'DCN', 'deform_groups': 1}

In [3]: build_conv_layer(dcn, 10, 10)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-03de5b270b07> in <module>
----> 1 build_conv_layer(dcn, 10, 10)

~/anaconda3/envs/mmdet/lib/python3.6/site-packages/mmcv/cnn/bricks/conv.py in build_conv_layer(cfg, *args, **kwargs)
     35     layer_type = cfg_.pop('type')
     36     if layer_type not in CONV_LAYERS:
---> 37         raise KeyError(f'Unrecognized norm type {layer_type}')
     38     else:
     39         conv_layer = CONV_LAYERS.get(layer_type)

KeyError: 'Unrecognized norm type DCN'
```
The mmcv version is 1.1.5, and I can import DCN with `from mmcv.ops import DeformConv2dPack` correctly. Is there something I miss?

**Comment by Pluto1314** [comment]
I have same error...

**Comment by ycxioooong** [comment]
Bug fixed in newer versions, e.g., mmcv-full >= 1.2.5

**Comment by zhongqiu1245** [comment]
Hi@ycxioooong 
This bug still exists.(my version of mmcv-full : 1.2.6)
<img width="710" alt="无标题" src="https://user-images.githubusercontent.com/48090608/114055126-0e3f3480-98c3-11eb-8b76-93883935ef22.png">
